#include <gtest/gtest.h>
#include <peglib.h>

// Define a custom AST node type for testing
struct CustomAstNode {
    std::string name;
    std::vector<CustomAstNode> children;
};

// Custom AST builder function
std::shared_ptr<CustomAstNode> custom_ast_builder(const peg::Ast& ast) {
    auto node = std::make_shared<CustomAstNode>();
    node->name = ast.name;
    for (const auto& child : ast.nodes) {
        node->children.push_back(*custom_ast_builder(*child));
    }
    return node;
}

TEST(EnableAstTest, BasicGrammarWithDefaultAst) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    // Enable AST generation with default Ast type
    parser.enable_ast();

    std::shared_ptr<peg::Ast> ast;
    bool ret = parser.parse("ab", ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(ast, nullptr);
    ASSERT_EQ(ast->name, "ROOT");
    ASSERT_EQ(ast->nodes.size(), 2);
    ASSERT_EQ(ast->nodes[0]->name, "A");
    ASSERT_EQ(ast->nodes[0]->token, "a");
    ASSERT_EQ(ast->nodes[1]->name, "B");
    ASSERT_EQ(ast->nodes[1]->token, "b");
}

TEST(EnableAstTest, GrammarWithExistingActionsAndDefaultAst) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    // Add an action to rule A before enabling AST
    parser["A"] = [](const peg::SemanticValues& sv) {
        return sv.token();
    };

    // Enable AST generation with default Ast type
    parser.enable_ast();

    std::shared_ptr<peg::Ast> ast;
    bool ret = parser.parse("ab", ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(ast, nullptr);
    ASSERT_EQ(ast->name, "ROOT");
    ASSERT_EQ(ast->nodes.size(), 2);
    // Rule A should still have its custom action, so it won't generate an AST node by default
    // The default enable_ast only adds actions if one doesn't exist.
    ASSERT_EQ(ast->nodes[0]->name, "A"); // Still an AST node, but its content might be affected by the action
    ASSERT_EQ(ast->nodes[0]->token, "a");
    ASSERT_EQ(ast->nodes[1]->name, "B");
    ASSERT_EQ(ast->nodes[1]->token, "b");
}

TEST(EnableAstTest, EmptyGrammar) {
    peg::parser parser(""); // Empty grammar

    ASSERT_FALSE(parser.valid()); // An empty grammar is not valid

    // Calling enable_ast on an invalid parser should not crash and should return *this
    parser.enable_ast();

    // No meaningful parse can be done, but we ensure it doesn't crash.
    // The internal grammar_ will be empty, so the loop in enable_ast won't execute.
}

TEST(EnableAstTest, GrammarWithNoRules) {
    peg::parser parser(R"(
        // No rules defined
    )");

    ASSERT_TRUE(parser.valid()); // A grammar with no rules but valid syntax is valid

    // Enable AST generation
    parser.enable_ast();

    // No rules means no actions to add, so it should just return *this
    // No crash expected.
}

TEST(EnableAstTest, GrammarWithCustomAstType) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    // Enable AST generation with a custom Ast type
    parser.enable_ast<CustomAstNode>();

    // Set the custom AST builder
    parser.set_ast_builder(custom_ast_builder);

    std::shared_ptr<CustomAstNode> custom_ast;
    bool ret = parser.parse("ab", custom_ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(custom_ast, nullptr);
    ASSERT_EQ(custom_ast->name, "ROOT");
    ASSERT_EQ(custom_ast->children.size(), 2);
    ASSERT_EQ(custom_ast->children[0].name, "A");
    ASSERT_EQ(custom_ast->children[1].name, "B");
}

TEST(EnableAstTest, GrammarWithCustomAstTypeAndExistingActions) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    // Add an action to rule A before enabling AST
    parser["A"] = [](const peg::SemanticValues& sv) {
        return sv.token();
    };

    // Enable AST generation with a custom Ast type
    parser.enable_ast<CustomAstNode>();

    // Set the custom AST builder
    parser.set_ast_builder(custom_ast_builder);

    std::shared_ptr<CustomAstNode> custom_ast;
    bool ret = parser.parse("ab", custom_ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(custom_ast, nullptr);
    ASSERT_EQ(custom_ast->name, "ROOT");
    ASSERT_EQ(custom_ast->children.size(), 2);
    // Rule A should still have its custom action, so enable_ast should not override it.
    // The custom_ast_builder will still be called for the Ast node generated by the default action.
    ASSERT_EQ(custom_ast->children[0].name, "A");
    ASSERT_EQ(custom_ast->children[1].name, "B");
}

TEST(EnableAstTest, MultipleCallsToEnableAst) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    // First call with default Ast
    parser.enable_ast();

    // Second call with custom Ast type
    parser.enable_ast<CustomAstNode>();

    // Set the custom AST builder
    parser.set_ast_builder(custom_ast_builder);

    std::shared_ptr<CustomAstNode> custom_ast;
    bool ret = parser.parse("ab", custom_ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(custom_ast, nullptr);
    ASSERT_EQ(custom_ast->name, "ROOT");
    ASSERT_EQ(custom_ast->children.size(), 2);
    ASSERT_EQ(custom_ast->children[0].name, "A");
    ASSERT_EQ(custom_ast->children[1].name, "B");

    // Verify that the actions are correctly set for the custom type
    // This implies that the last enable_ast call takes precedence for rules without existing actions.
    // The internal mechanism of enable_ast is to add an action IF one doesn't exist.
    // So, the first call adds default Ast actions. The second call, if it finds an existing action,
    // will not overwrite it. However, the type parameter T in enable_ast<T> affects the type
    // of AST node created by the default action, which is then passed to the ast_builder.
    // The key is that the ast_builder is set globally for the parser.
}

TEST(EnableAstTest, EnableAstThenDisableAst) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    parser.enable_ast();

    // Disabling AST should remove the default AST actions
    parser.disable_ast();

    std::shared_ptr<peg::Ast> ast;
    bool ret = parser.parse("ab", ast);

    ASSERT_TRUE(ret); // Parsing should still succeed
    ASSERT_EQ(ast, nullptr); // No AST should be generated
}

TEST(EnableAstTest, EnableAstThenDisableAstThenEnableAgain) {
    peg::parser parser(R"(
        ROOT <- A B
        A <- 'a'
        B <- 'b'
    )");

    ASSERT_TRUE(parser.valid());

    parser.enable_ast();
    parser.disable_ast();
    parser.enable_ast(); // Enable again

    std::shared_ptr<peg::Ast> ast;
    bool ret = parser.parse("ab", ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(ast, nullptr); // AST should be generated again
    ASSERT_EQ(ast->name, "ROOT");
}

TEST(EnableAstTest, GrammarWithRecursion) {
    peg::parser parser(R"(
        EXPR <- TERM (('+' / '-') TERM)*
        TERM <- FACTOR (('*' / '/') FACTOR)*
        FACTOR <- NUMBER / '(' EXPR ')'
        NUMBER <- [0-9]+
    )");

    ASSERT_TRUE(parser.valid());

    parser.enable_ast();

    std::shared_ptr<peg::Ast> ast;
    bool ret = parser.parse("1 + 2 * (3 - 4)", ast);

    ASSERT_TRUE(ret);
    ASSERT_NE(ast, nullptr);
    ASSERT_EQ(ast->name, "EXPR");
    ASSERT_EQ(ast->nodes.size(), 3); // TERM, '+', TERM
    ASSERT_EQ(ast->nodes[0]->name, "TERM");
    ASSERT_EQ(ast->nodes[1]->token, "+");
    ASSERT_EQ(ast->nodes[2]->name, "TERM");
    ASSERT_EQ(ast->nodes[2]->nodes.size(), 3); // FACTOR, '*', FACTOR
    ASSERT_EQ(ast->nodes[2]->nodes[0]->name, "FACTOR");
    ASSERT_EQ(ast->nodes[2]->nodes[0]->nodes[0]->name, "NUMBER");
    ASSERT_EQ(ast->nodes[2]->nodes[0]->nodes[0]->token, "2");
}